[env]
KUBECONFIG = '{{config_root}}/clusters/pi/kubeconfig:{{config_root}}/clusters/test/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'
#TALOSCONFIG = '{{config_root}}/kubernetes/pi/bootstrap/talos/clusterconfig/talosconfig:{{config_root}}/kubernetes/test/bootstrap/talos/clusterconfig/talosconfig'
