[env]
KUBECONFIG = '{{config_root}}/kubernetes/pi/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'
TALOSCONFIG = '{{config_root}}/kubernetes/pi/bootstrap/talos/clusterconfig/talosconfig'
