---
originRequest:
  originServerName: external-pi5.jory.dev

ingress:
  - hostname: jory.dev
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.jory.dev"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
