apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-shared
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:05kc/UhnDOE=,iv:oWKo8Oy4ZQFlZp6gBRZ7SD2IN2lBkliZMqus5pG+lEI=,tag:0/W2swJBbueglzSMtp7IsA==,type:str]
    SECRET_NFS_VOLSYNC: ENC[AES256_GCM,data:zi4Xas5UiBwJEcn1jOJgSG34mmBTvfaursImbQ==,iv:tsa17luCt7vZpmmul9fCcOpPAO51wbZWwIUl9YHdgAc=,tag:h3YghviJv7am+YVKKm0Obw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaG00WmxPWjIvRjRVTTh3
            V05uRFA2UmFXOFJIZmFnS3FvZVN0MkMvRVhjCmRqVnlQZDBOcUlzTzNTTDlvVnV4
            ZTJ2RWd1M00yeWFTWEJVWUZITkYxU0EKLS0tIFlPcEtiN1E4SUlKckpyVm9ram5C
            eG8vOG4zOXRQVW01K1hzNnNUdUxYNDQK2r6cmnIxsIDMUHfq8p0kOcr+E/KAea4z
            tdtvD/HkOfTil0Qwld0NWRyA4DKC7AjhC0P8QlhYrNlfr5lqBqIFmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T18:47:30Z"
    mac: ENC[AES256_GCM,data:+/CW6F3fxPo+F0TVbeb7H7AJotZFNnFaDumqkSjpWPgnyJE7OvMWCNqpr5az2kKr2+DSfBKoLp9INmgkDBVZ92Fx84shSFVX6gJF9MvKhcayvyN1UwtDaAsCOLJCnlac3sNg5mzYtJEpzUOJBKrZlaMSUs0cc56o2r9x0vZGrbU=,iv:pnfaHkMcSRM+UlMUO1AOxQvSQHCIyGOAwrYCKLrdkXU=,tag:Ju2Q/msArpN2Dns4RLcIaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
