apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:UuKFrVLNjwuYOFY=,iv:/PYG54F4Je1S0nCAUQwbRfN5nSeFl8bRCN/QcH7BFzs=,tag:qYwTAazDujY+kQWp5ZMI2w==,type:comment]
    SVC_KUBE_API: ENC[AES256_GCM,data:nU6NAO0WUOsgf18=,iv:dLjCkT8d1KVbuZmnnl+bjSRgxLAxHCwvahoeezN+S94=,tag:zYW5AgXkJXPYZumBep5HDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T17:10:47Z"
    mac: ENC[AES256_GCM,data:h9VPl7V4HREKyNLjWnz01VhabNIl2DGiEwIoqe9k1icZKhd33i/3W1GZiXcTc3CZrnuCkGv47B2gwL26wuDe2KDe6IIaD0Fr1CF0G1wEyxo8Kr7n4nraq9W9CpGvpAWO068C2QOOPoJsZ6ELDfJL7dLjrcJpS7WIqOAOp7L3rRw=,iv:1lcNSp0zvZqjVIAYnQIKYrl9DXXY3tta92S7CkvqGCs=,tag:nJFtGg3zm9do7fuvPSykIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
