---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    image:
      repository: ghcr.io/joryirving/volsync
      tag: 0.11.0@sha256:c47480e13eef5af9be91f4bd2b37b82efd8165972fcc59f549db74263fe88870
    manageCRDs: true
    metrics:
      disableAuth: true
