---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER: pi
  PVC_VOLSYNC_STORAGECLASS: local-hostpath
  VOLSYNC_SNAPSHOTCLASS: csi-local-hostpath
  VOLSYNC_CACHE_SNAPSHOTCLASS: local-hostpath
  VOLSYNC_STORAGECLASS: local-hostpath
  CLOUDFLARE_TUNNEL_MAIN_ID: 03ed8136-b897-4ec7-9928-88ec0576725e
