
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: network
spec:
  values:
    controllers:
      cloudflared:
        containers:
          app:
            args:
              - tunnel
              - --config
              - /etc/cloudflared/config/config.yaml
              - run
              - 03ed8136-b897-4ec7-9928-88ec0576725e
